# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ddfb62e8d028e6f67eb06a1eb42e06a7bdd8fb6b89b8107d94a1200e7a8a9c4cd762fc0ae3a8cb5b8ba759460d4714acf679069aaca6e20b3a9d12f95ee8625

test:
  secret_key_base: 4ce85cd668a5901c0ad2602e980eecb6183707cac3f24b41a3f9bc7f0bd44c40e29c0473c2be3459dce57fbf44eb5c3471f8aa56f66a0ac33c2789e4e434fca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
